---
-  name: replace .env
   copy:
      src: .env
      dest: /var/www/snipeit/.env
-  name: replace php.ini
   copy:
      src: php.ini
      dest: /etc/php/8.1/apache2/php.ini
-  name: replace snipeit.conf
   copy:
      src: snipeit.conf
      dest: /etc/apache2/sites-available/snipeit.conf
- name: Copy my.cnf.j2 to remote machine
   copy:
      src: files/my.cnf.j2
      dest: /root/.my.cnf
    become: yes

